setting_name: CHESS_IR_CG_RT_QT_MOCK

team_agents:
  information_retriever:
    engine: "gemini-2.0-flash-lite"
    tools:
      extract_keywords:
        template_name: "extract_keywords"
        engine_config:
          engine_name: "gemini-2.0-flash-lite"
          temperature: 0.2
        parser_name: "python_list_output_parser"
      retrieve_entity: {}
      retrieve_context:
        top_k: 5

  candidate_generator:
    engine: "gemini-2.0-flash-lite"
    tools:
      generate_candidate:
        generator_configs:
          - template_name: "generate_candidate_one"
            engine_config:
              engine_name: "gemini-2.0-flash-lite"
              temperature: 0.5
            parser_name: "generate_candidate_gemini_markdown_cot"
            sampling_count: 10
          - template_name: "generate_candidate_two"
            engine_config:
              engine_name: "gemini-2.0-flash-lite"
              temperature: 0.5
            parser_name: "generate_candidate_gemini_markdown_cot"
            sampling_count: 10

      revise:
        template_name: "revise_one"
        engine_config:
          engine_name: "gemini-2.0-flash-lite"
          temperature: 0.0
        parser_name: "revise_new"

  mock_db_tester:
    engine: "gemini-2.0-flash-lite"
    tools:
      mock_database_generator:
        template_name: "mock_db_generate"
        engine_config:
          engine_name: "gemini-2.0-flash-lite"
          temperature: 0.0
        parser_name: "list_output_parser"
      mock_answer_generator:
        template_name: "mock_answer_generate"
        engine_config:
          engine_name: "gemini-2.0-flash-lite"
          temperature: 0.0
        parser_name: "select_tables"
      mock_sql_decision: {}
